Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -10,26 +10,20 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-
-      - name: Setup .NET
-        uses: actions/setup-dotnet@v2
-        with:
-          dotnet-version: 6.0.x
-
-      - name: Restore dependencies
-        run: dotnet restore Newwebapiproject.sln
-
-      - name: Build
-        run: dotnet build Newwebapiproject.sln --no-restore
-
-      - name: Run Unit Tests
-        run: dotnet test ./Newwebapiproject.Tests/Newwebapiproject.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
-
-      - name: Check Unit Test Status
-        run: |
-          if [ $? -ne 0 ]; then
-            echo "Unit tests failed. Preventing merge."
-            exit 1
-          fi
+    - uses: actions/checkout@v3
+    - name: Setup .NET
+      uses: actions/setup-dotnet@v3
+      with:
+        dotnet-version: 6.0.x
+    - name: Restore dependencies
+      run: dotnet restore Newwebapiproject.sln
+    - name: Build
+      run: dotnet build Newwebapiproject.sln --no-restore
+    - name: Test
+      run: |
+        dotnet test ./Newwebapiproject.Tests/Newwebapiproject.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
+        test_exit_code=$?
+        if [ $test_exit_code -ne 0 ]; then
+          echo "Unit tests failed. Preventing merge $test_exit_code."
+          exit $test_exit_code
+        fi
