Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -1,19 +1,14 @@
-# This workflow will build a .NET project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net
-
 name: .NET
 
 on:
   push:
-    branches: [ "master" ]
+    branches: [ "master" ]  
   pull_request:
-    branches: [ "master" ]
+    branches: [ "master" ]  
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
-
     steps:
     - uses: actions/checkout@v3
     - name: Setup .NET
@@ -25,11 +20,11 @@ jobs:
     - name: Build
       run: dotnet build Newwebapiproject.sln --no-restore
     - name: Test
-           test_exit_code=0
-           dotnet build
-      run: dotnet test ./Newwebapiproject.Tests/Newwebapiproject.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
-           test_exit_code=$?
-           if [ $test_exit_code -ne 0 ]; then
-            echo "Unit tests failed. Preventing merge."
-            exit 1
-           fi
+      run: |
+        test_exit_code=0
+        dotnet test ./Newwebapiproject.Tests/Newwebapiproject.Tests.csproj --no-build --verbosity normal --collect:"XPlat Code Coverage"
+        test_exit_code=$?
+        if [ $test_exit_code -ne 0 ]; then
+          echo "Unit tests failed. Preventing merge."
+          exit 1
+        fi
